### ISSUE TITLE
Why only local fields?

### ISSUE THREAD

**Issue by mitar** [smn/django-dirtyfields#2]
Why are only local fields checked for changes and not all fields?

**Comment by erichonkanen** [comment]
yes yes yes! I found this and thought "oh how cool!", until I realized it doesnt work for foreignkey :(

**Comment by smn** [comment]
There are multiple people asking for this. I'm more than happy to review any contributed code.

**Comment by erichonkanen** [comment]
I'll take a stab at it soon if no one else does... found this too which may or may not apply http://www.netlandish.com/blog/2013/12/14/easily-track-data-changes-in-your-django-models/

**Comment by romgar** [comment]
This issue can be closed, because of PR #16 ?

**Comment by romgar** [comment]
Foreign keys are now managed with `check_relationship` parameter.

For m2m relations, we are adding new instances to an object with `.add()` method, that is saving them in db. Dirtyfield is then useless in that case.
