### ISSUE TITLE
pip install django-dirtyfields doesn't pull the most up-to-date code

### ISSUE THREAD

**Issue by prathapsridharan** [smn/django-dirtyfields#20]
pip install django-dirtyfields 

doesn't pull the correct codebase.

For instance, is_dirty doesn't even have the check_relationship param as per the code downloaded. For now I am working around this by making pip download from head of master branch.

**Comment by romgar** [comment]
Hi @prathapsridharan ,

We have not yet released the latest version on pypi. @smn , I think it can be good to talk about when releasing a new version.

**Comment by prathapsridharan** [comment]
Thank you! I figured that might have been the case but just wanted to let you know if there was indeed some other issue.

Cheers,

Prathap

**Comment by smn** [comment]
@romgar if you follow the Git flow release process it'll result in a new release on Pypi. Just make sure to update the version number and have it conform with semver.org's recommendations on what the next reasonable version number is?

**Comment by romgar** [comment]
Ok !!

**Comment by angelo-romano** [comment]
wanted to ask the same actually. Any short term plans for a new version release? that'd be great, indeed the check_relationship improvement would be quite helpful for a task I'm working on right now. Keep up the good work, by the way!

**Comment by romgar** [comment]
Hi @angelo-romano , I expect to spend some time really soon (days).

**Comment by romgar** [comment]
@angelo-romano version 0.4 (with `check_relationship`) is released, enjoy !

**Comment by smn** [comment]
nice work @romgar, thank you.
