### ISSUE TITLE
Empty models.py not needed

### ISSUE THREAD

**Issue by mjtamlyn** [smn/django-dirtyfields#23]
Since the [app loading refactor](https://docs.djangoproject.com/fr/1.7/releases/1.7/#app-loading-refactor) in Django 1.7, there has been no need for installed apps to have an empty `models.py`. Given that this doesn't actually need to be an installed app at all, there's no need to have it anyway.

**Comment by romgar** [comment]
I would like to support Django 1.4+ for now, as 1.4 support ends only in October 2015.

But you are right that we don't need to add it to `INSTALLED_APPS`, so I will remove it.

**Comment by romgar** [comment]
Fixed on last released version (0.4.1).
