### ISSUE TITLE
Can not create new object

### ISSUE THREAD

**Issue by busy** [smn/django-dirtyfields#26]
I try to use your app, for early created object it work, but when i try create new object with ForeignKey i catch error "RelatedObjectDoesNotExist"

class TestObject(DirtyFieldsMixin):
    category = models.ForeignKey(Category)
    title = models.CharField('Title', max_length=255, blank=True, default='')

**Comment by romgar** [comment]
Hi @busy ! Thanks for reporting. I have reproduced this problem, and will fix it soon.

**Comment by jazzywhit** [comment]
:facepalm: I should have looked here first :)

**Comment by romgar** [comment]
@jazzywhit Yep ! No worries.

**Comment by romgar** [comment]
Fixed in 0.5 (released today).
