### ISSUE TITLE
Not working with Python3

### ISSUE THREAD

**Issue by brennerm** [smn/django-dirtyfields#29]
The ```get_dirty_fields``` function uses ```dict.iteritems()``` which has been removed in Python3. Can we find a fix for that?

**Comment by brennerm** [comment]
A workaround for now is to replace ```for key, value in new_state.iteritems():``` with ```for key, value in new_state.items():``` in dirtyfields.py:31. Using this with Python2 creates a list of tuples, which can be memory expensive.

**Comment by smn** [comment]
Thanks for raising, more than happy to look at a pull-request that would add support for py3.

**Comment by brennerm** [comment]
There you go ;)
https://github.com/smn/django-dirtyfields/pull/30

**Comment by romgar** [comment]
For that kind of compatibility problem, it could be more interesting to use something like six, that is used for python 2/3 compatibility (https://pythonhosted.org/six/)

**Comment by romgar** [comment]
#30 has fixed this (and #31 has added py3 travis support)
