### ISSUE TITLE
Model loading issue after upgrade to 0.4

### ISSUE THREAD

**Issue by wolfg1969** [smn/django-dirtyfields#34]
I have a model with multiple foreign keys. After upgrade to 0.4, it is very slow to loading the model objects, since there are a lot of queries for relation objects, even for getting a single object. Obviously it is a N+1 query problem.

**Comment by romgar** [comment]
Hi @wolfg1969 ! I guess that you are using `check_relationship=True` option ?

For now, we are getting foreign key model instance on dirty field checking, but it could be a better idea to get `<fk_field_name>_id` value to avoid that extra query on each `ForeignKey` field.

**Comment by wolfg1969** [comment]
@romgar I don't call ```get_dirty_fields``` method on model instance. I just make a model querying like this ```Model.objects.filter(...)```. I guess the cause is that the ```reset_state``` function set  ```check_relationship=True``` option when calling ```_as_dict``` and it is called in instance ```__init__``` method.

**Comment by romgar** [comment]
@wolfg1969 Thanks for details. I will fix that.

**Comment by romgar** [comment]
@wolfg1969 I don't easily manage to reproduce your problem. Can you give me some code example (how you define your model, how you call it, ideally create a test case), so that I can use it to be sure I resolve this issue ?

**Comment by wolfg1969** [comment]
Hi @romgar I write a test case for this issue, you can download the patch from https://github.com/smn/django-dirtyfields/pull/35.patch . The PR can be ignored. Hope this will help you.

**Comment by romgar** [comment]
Great work @wolfg1969 !!

I will merge your PR (you deserve to appear in contributor list), and just improve 2-3 little things (use @override_settings decorator for `DEBUG=True`, move `query_num` in another file, ...).

Thanks again !

**Comment by wolfg1969** [comment]
@romgar :+1:

**Comment by romgar** [comment]
I think that I will release a new minor version of django_dirtyfields with this fix, as we are now returning foreign key ids instead of model instances on `get_dirty_fields()` .
