### ISSUE TITLE
KeyError when foreign key is initially set.

### ISSUE THREAD

**Issue by dalberto** [smn/django-dirtyfields#37]
I've encountered an issue where dirtyfields throws a `KeyError` when `check_relationship=True` and a model is initially being saved, so `_original_state` is an empty dictionary. The fix is simple but I'm not sure if it would cause unexpected behavior for others.

The fix can be found here:
https://github.com/dalberto/django-dirtyfields/commit/fa4056b775d8ef3cc05a42b28d186497eb3892b0

**Comment by romgar** [comment]
Hi @dalberto, can you write a test case to reproduce it ?

**Comment by romgar** [comment]
Or at least, give an example of your model(s) and how you have used dirtyfields ?

**Comment by dalberto** [comment]
Hmm, I tried to reproduce in an isolated environment and it doesn't seem like this is an issue anymore.

**Comment by romgar** [comment]
Good news ! Thanks for reporting and closing !!
