### ISSUE TITLE
New Pypi release

### ISSUE THREAD

**Issue by MounirMesselmeni** [smn/django-dirtyfields#38]
There is a big performance issue on the current version "0.5" with the related fields (FK or o2o), SQL queries count (Using Debug toolbar) can be from 20 to 400 and even more with this update (from "0.3" to "0.5")
This is not the case when installing directly from git.

Thanks

**Comment by romgar** [comment]
Hi @MounirMesselmeni !
The new release (0.6) will be deployed soon (few days) to fix that.
Thanks for reporting.

**Comment by MounirMesselmeni** [comment]
Thank you very much :+1:

**Comment by romgar** [comment]
0.6 released !
