### ISSUE TITLE
Doesn't take internal conversions into account

### ISSUE THREAD

**Issue by nazgul** [smn/django-dirtyfields#4]
With MySQL, I can pass a string "1" to an integer value, and somewhere along the line (Django? MySQL?) it will convert it as appropriate. However the comparisons performed by the mixin will attempt to compare the string I passed with the integer from the database, and since Python (for reasons that completely escape me…this burns me all the time), will not throw an error on the invalid comparison, but will simply return false. The result is that records will be marked dirty when in fact things have not changed.

I'm not sure how to fix this other than by replicating all the conversions prior to the first call to check for dirty fields. Or else to have the check for dirty fields do the conversions on the fly, which seems inefficient (remember, this includes converting strings to dates). Of course, this means it needs to deal with exceptions if bad data has been passed in (although perhaps in that case it's okay to just say "it's dirty").

**Comment by romgar** [comment]
Hi @jimrollenhagen , I'm just reviewing every old issue/pull request (3 years for this one...), so I will do something shortly about that issue.
