### ISSUE TITLE
Update PyPI?

### ISSUE THREAD

**Issue by heston** [smn/django-dirtyfields#7]
Any chance you could update the version on PyPI? We're using this in production, and just ran into an issue with it that's fixed in master, but not in PyPI (v0.1).

Also, I saw you may be looking for a new owner of django-dirtyfields. I'd be happy to fill the role, if you still have a need.

**Comment by smn** [comment]
@romgar added you as a contributor. 

I've also switched to `develop` as the main branch, I'm used to using the Git Flow way of working. 
1. Development happens in feature branches
2. Pull requests against develop
3. Releases happen off of develop
4. Master always at the latest release
5. Releases result in a tag in git which results in an automatic deploy to Pypi from Travis (assuming the version number's been bumped successfully).

Happy coding.

**Comment by smn** [comment]
Also, when version bumping please stick with semver.org's recommendations.

**Comment by romgar** [comment]
Great, thanks !
I'm more used to use master as the latest one, and create branches/tags for releases, but ok to follow your recommendations :-)

**Comment by smn** [comment]
Cool, fwiw [here's the background info](http://nvie.com/posts/a-successful-git-branching-model/) on git flow and [here's some info on installing the command line helpers](https://github.com/nvie/gitflow/wiki/Installation).

**Comment by romgar** [comment]
I will have a look at it !
